#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/ncl/bin

dia=`date  +%d`
mes=`date  +%m`
anio=`date +%Y`

#<<<<<<< HEAD
#in=\"/home/lili/Escritorio/repos/ncl/\"
#out=\"/home/lili/Escritorio/repos/ncl/out/wrf/\"

#in=\"/home/CENAPRED/Data/WRF/\"
#out=\"/home/CENAPRED/Data/WRF/out/\"

#in=\"/ServerData/WRF-OMETEOTL/EXTERNO-salidas/WRF/\"
#out=\"/home/liliana/out/WRF/\"

in=\"/ServerData/Pronosticos/Salidas/WRF/\"
out=\"/ServerData/OWGIS/WRF/\"

echo begin WRF>> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
date >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
ncl dia=$dia mes=$mes anio=$anio "in=${in}" "out=${out}" /ServerScripts/WRF_to_OWGIS/WRF_for_OWGIS_LOCAL.ncl >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt 
echo finish WRF >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
date >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
echo  ------------------------------------- >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
echo  ------------------------------------- >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt

#find /ServerData/OWGIS/WRF/ -type f -size -600M -delete
pwd
cd /ServerData	
cd OWGIS
cd WRF
pwd
find  -name "*.nc" -size -600M -delete
