#!/bin/bash

#dia=`date  +%d`
dia=`date  +%d`
mes=`date  +%m`
anio=`date +%Y`

in=\"/ServerData/Pronosticos/Salidas/ADCIRC/\"
out=\"/ServerData/OWGIS/ADCIRC/\"

ncl dia=$dia mes=$mes anio=$anio "in=${in}" "out=${out}" ADCIRC_to_OWGIS.ncl
