#!/bin/bash

dia=`date  +%d`
mes=`date  +%m`
anio=`date +%Y`

#<<<<<<< HEAD
in=\"/home/lili/Escritorio/repos/ncl/SIPROMAT/\"
out=\"/home/lili/Escritorio/repos/ncl/out/adcirc/\"

#in=\"/home/CENAPRED/Data/ADCIRC/\"
#out=\"/home/CENAPRED/Data/ADCIRC/out/\"

#in=\"/DATA/WRF/\"
#out=\"/DATA/OUT/WRF/\"


#COMMAND= "ncl DATE rfile WRF_for_OWGIS_LOCAL.ncl"
#COMMAND="ls -d -1 /home/lili/Escritorio/repos/ncl-Tools/WRF/* | grep -v '$DATE' | xargs rm -f"
#echo "Removing files with: $COMMAND"

#COMMAND= ncl rfile=\"/home/lili/Escritorio/repos/ncl/\" dia=$dia mes=$mes anio=$anio WW3_for_OWGIS_LOCAL.ncl
#eval $COMMAND

ncl dia=$dia mes=$mes anio=$anio "in=${in}" "out=${out}" ADCIRC_for_OWGIS_LOCAL.ncl
