#!/bin/bash

dia=`date  +%d`
mes=`date  +%m`
anio=`date +%Y`

#<<<<<<< HEAD
#in=\"/home/lili/Escritorio/repos/ncl/oleaje/salidas_dominio_golfo/\"
#out=\"/home/lili/Escritorio/repos/ncl/out/oleaje/\"

#in=\"/home/CENAPRED/Data/oleaje/\"
#out=\"/home/CENAPRED/Data/oleaje/out/\"

#in=\"/DATA/WRF/\"
#out=\"/DATA/OUT/WRF/\"

in=\"/ServerData/Pronosticos/Salidas/WWIII/\"
out=\"/ServerData/OWGIS/WWIII/\"

#COMMAND= "ncl DATE rfile WRF_for_OWGIS_LOCAL.ncl"
#COMMAND="ls -d -1 /home/lili/Escritorio/repos/ncl-Tools/WRF/* | grep -v '$DATE' | xargs rm -f"
#echo "Removing files with: $COMMAND"

#COMMAND= ncl rfile=\"/home/lili/Escritorio/repos/ncl/\" dia=$dia mes=$mes anio=$anio WW3_for_OWGIS_LOCAL.ncl
#eval $COMMAND

ncl dia=$dia mes=$mes anio=$anio "in=${in}" "out=${out}" /ServerScripts/WWIII_to_OWGIS/WW3_for_OWGIS_LOCAL.ncl

echo finish wwiii $dia/$mes/$anio >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt

