#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/ncl/bin

dia=`date  +%d`
mes=`date  +%m`
anio=`date +%Y`

#<<<<<<< HEAD
#in=\"/home/lili/Escritorio/repos/ncl/oleaje/salidas_dominio_golfo/\"
#out=\"/home/lili/Escritorio/repos/ncl/out/oleaje/\"

#in=\"/home/CENAPRED/Data/oleaje/\"
#out=\"/home/CENAPRED/Data/oleaje/out/\"

#in=\"/DATA/WRF/\"
#out=\"/DATA/OUT/WRF/\"

in=\"/ServerData/Pronosticos/Salidas/WWIII/\"
out=\"/ServerData/OWGIS/WWIII/\"

#COMMAND= "ncl DATE rfile WRF_for_OWGIS_LOCAL.ncl"
#COMMAND="ls -d -1 /home/lili/Escritorio/repos/ncl-Tools/WRF/* | grep -v '$DATE' | xargs rm -f"
#echo "Removing files with: $COMMAND"

#COMMAND= ncl rfile=\"/home/lili/Escritorio/repos/ncl/\" dia=$dia mes=$mes anio=$anio WW3_for_OWGIS_LOCAL.ncl
#eval $COMMAND

echo begin WWIII >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
date  >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
ncl dia=$dia mes=$mes anio=$anio "in=${in}" "out=${out}" /ServerScripts/WWIII_to_OWGIS/WW3_for_OWGIS_LOCAL.ncl >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
echo finish WWIII $dia/$mes/$anio >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
date  >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
echo  ------------------------------------- >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
echo  ------------------------------------- >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt

#find /ServerData/OWGIS/WWIII/ -type f -size -10M -delete
pwd
cd /ServerData	
cd OWGIS
cd WWIII
pwd
find  -name "*.nc" -size -10M -delete

