#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/ncl/bin
dia=`date  +%d`
mes=`date  +%m`
anio=`date +%Y`


echo begin GFS >> /ServerScripts/Logs/log_day1_$dia-$mes-$anio.txt
date >> /ServerScripts/Logs/log_day1_$dia-$mes-$anio.txt

ncl /ServerScripts/GFS_to_OWGIS/GribToNetcdfOWGIS.ncl  >> /ServerScripts/Logs/log_day1_$dia-$mes-$anio.txt

echo finish GFS $dia/$mes/$anio >> /ServerScripts/Logs/log_day1_$dia-$mes-$anio.txt
date >> /ServerScripts/Logs/log_day1_$dia-$mes-$anio.txt
echo  ------------------------------------- >> /ServerScripts/Logs/log_day1_$dia-$mes-$anio.txt
echo  ------------------------------------- >> /ServerScripts/Logs/log_day1_$dia-$mes-$anio.txt

#find /ServerData/OWGIS/GFS/ -type f -size -10M -delete
pwd
cd /ServerData	
cd OWGIS
cd GFS
pwd
find  -name "*.nc" -size -10M -delete

