#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/ncl/bin

dia=`date  +%d`
mes=`date  +%m`
anio=`date +%Y`

in_otro=\"/ServerData/OWGIS/percentiles\"
in=\"/ServerData/Pronosticos/Salidas/WRF/\"
out=\"/ServerData/OWGIS/WRF/\"

echo begin WRF>> /ServerScripts/Logs/log_day2_$dia-$mes-$anio.txt
date >> /ServerScripts/Logs/log_day2_$dia-$mes-$anio.txt
ncl dia=$dia mes=$mes anio=$anio "in=${in}" "in_otro=${in_otro}" "out=${out}" /ServerScripts/WRF_to_OWGIS/WRF_for_OWGIS_LOCAL_prueba_resolucion.ncl 


