#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/ncl/bin

dia=`date  +%d`
mes=`date  +%m`
anio=`date +%Y`

in=\"/ServerData/Pronosticos/Salidas/ADCIRC/\"
out=\"/ServerData/OWGIS/ADCIRC/\"

echo begin ADCIRC >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
date >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
ncl dia=$dia mes=$mes anio=$anio "in=${in}" "out=${out}" /ServerScripts/ADCIRC_to_OWGIS/ADCIRC_to_OWGIS.ncl >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
echo finish ADCIRC $dia/$mes/$anio >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
date >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
echo  ------------------------------------- >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
echo  ------------------------------------- >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt

#DAY=`date --date="1 day ago" +%d`
#MONTH=`date --date="1 day ago" +%m`
#YEAR=`date date="1 day ago" +%Y`
#rm /ServerScripts/Logs/log_day_$DAY-$MONTH-$YEAR.txt

#find /ServerData/OWGIS/ACDIRC/*.nc -type f -size -1M -delete
pwd
cd /ServerData	
cd OWGIS
cd ADCIRC
pwd
find  -name "*.nc" -size -10M -delete

