#!/bin/bash

dia=`date  +%d`
mes=`date  +%m`
anio=`date +%Y`

#<<<<<<< HEAD
#in=\"/home/lili/Escritorio/repos/ncl/\"
#out=\"/home/lili/Escritorio/repos/ncl/out/wrf/\"

#in=\"/home/CENAPRED/Data/WRF/\"
#out=\"/home/CENAPRED/Data/WRF/out/\"

#in=\"/ServerData/WRF-OMETEOTL/EXTERNO-salidas/WRF/\"
#out=\"/home/liliana/out/WRF/\"


#in=\"/ServerData/Pronosticos/Salidas/WRF/\"
#out=\"/ServerData/OWGIS/WRF/\"


in=\"/TEMPOMETEOTL/EXTERNO-salidas/WRF-CHEM/mexico/\"
out=\"/ServerData/OWGIS/WRF/\"

#COMMAND= "ncl DATE rfile WRF_for_OWGIS_LOCAL.ncl"
#COMMAND="ls -d -1 /home/lili/Escritorio/repos/ncl-Tools/WRF/* | grep -v '$DATE' | xargs rm -f"
#echo "Removing files with: $COMMAND"

#COMMAND= ncl rfile=\"/home/lili/Escritorio/repos/ncl/\" dia=$dia mes=$mes anio=$anio WRF_for_OWGIS_LOCAL.ncl
#eval $COMMAND

ncl dia=$dia mes=$mes anio=$anio "in=${in}" "out=${out}" /ServerScripts/WRF-CHEM_to_OWGIS/WRF-CHEM_for_OWGIS_LOCAL.ncl
echo finish WRF-CHEM $dia/$mes/$anio >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
