#!/bin/bash

dia=`date  +%d`
mes=`date  +%m`
anio=`date +%Y`

#COMMAND= ncl rfile=\"/home/lili/Escritorio/repos/ncl/\" dia=$dia mes=$mes anio=$anio rfile_init=\"/home/lili/Escritorio/repos/ncl-Tools/WRF/init/\" rfile_prec=\"/home/lili/Escritorio/repos/ncl-Tools/WRF/init/\" WRF_for_OWGIS_LOCAL.ncl

COMMAND= ncl rfile=\"/home/lili/Escritorio/repos/ncl/\" dia=$dia mes=$mes anio=$anio WRF_for_OWGIS_LOCAL.ncl

eval $COMMAND




