#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/ncl/bin


dia=`date  +%d`
mes=`date  +%m`
anio=`date +%Y`

#<<<<<<< HEAD
in=\"/home/lili/Escritorio/repos/ncl/disp_ceniza/\"
out=\"/home/lili/Escritorio/repos/ncl/out/disp_ceniza/\"

#in=\"/home/CENAPRED/Data/dispersion_ceniza/\"
#out=\"/home/CENAPRED/Data/dispersion_ceniza/out/\"

#in=\"/DATA/WRF/\"
#out=\"/DATA/OUT/WRF/\"

in=\"/ServerData/PronosticosExt/EXTERNO-salidas/FALL3D/\"
out=\"/ServerData/OWGIS/FALL3D/\"

echo begin FALL3D>> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
date >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt

ncl dia=$dia mes=$mes anio=$anio "in=${in}" "out=${out}" /ServerScripts/FALL3D_to_OWGIS/FALL3D_for_OWGIS_LOCAL.ncl >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt 
echo finish FALL3D >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
date >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
echo  ------------------------------------- >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt
echo  ------------------------------------- >> /ServerScripts/Logs/log_day_$dia-$mes-$anio.txt

#find /ServerData/OWGIS/FALL3D/ -type f -size -600M -delete
pwd
cd /ServerData	
cd OWGIS
cd FALL3D
pwd
find  -name "*.nc" -size -200M -delete
