#!/bin/bash


#se exporta la ruta de python
PYTHON="/usr/local/anaconda/bin/python"
ROOT="/home/vladimir/CENAPRED/Alertas"
PERCENTILES="Alertas.py"


#archivo donde se encuentran los percentiles
PER_FILE="/ServerData/OutTempRaul/percentil/Percentiles.nc"
#archivo donde se encuentran los pronosticos
FCT_FILE="/ServerData/Pronosticos/Salidas/WRF"
#archivo de salida
OUT=""

pushd . > /dev/null 2>&1

cd $ROOT

$PYTHON "$PERCENTILES" "$OUT" "$FCT_FILE" "$PER_FILE" > log/backup.txt 2>&1

popd > /dev/null 2>&1
